name: Sync_Download

permissions:
  contents: write
  actions: write

on: 
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  sync_download:
    runs-on: windows-2019
    env:
      GENDLOOP_ACCESS_TOKEN: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
    steps:
      - name: sync-download
        uses: gendloop/sync-download@main
